from pyswip import Prolog
prolog = Prolog()
prolog.assertz("progenitor(sara,isaque)")
prolog.assertz("progenitor(abraão,isaque)")
prolog.assertz("progenitor(abraão,ismael)")
prolog.assertz("progenitor(isaque,esaú)")
prolog.assertz("progenitor(isaque,jacó)")
prolog.assertz("progenitor(jacó,josé)")
prolog.assertz("mulher(sara)")
prolog.assertz("homem(abraão)")
prolog.assertz("homem(isaque)")
prolog.assertz("homem(ismael)")
prolog.assertz("homem(esaú)")
prolog.assertz("homem(jacó)")
prolog.assertz("homem(josé)")
prolog.assertz("filho(Y,X) :- progenitor(X,Y)")
prolog.assertz("mae(X,Y) :- progenitor(X,Y), mulher(X)")
prolog.assertz("avo(X,Z) :- progenitor(X,Y), progenitor(Y,Z)")
prolog.assertz("irmão(X,Y) :- progenitor(Z,X), progenitor(Z,Y)")
prolog.assertz("ancestral(X,Z) :- progenitor(X,Z)")
prolog.assertz("ancestral(X,Z) :- progenitor(X,Y), ancestral(Y,Z)")